apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
        - name: flask-hello-world
          image: docker.io/library/flask-hello-world:latest
          imagePullPolicy: Never        # critical — use local image, don't pull from hub
          ports:
            - containerPort: 5000
